services:
    dmzx.yourpostcount.listener:
        class: dmzx\yourpostcount\event\listener
        arguments:
            - @template
            - @user
            - @dbal.conn
        tags:
            - { name: event.listener }